spring.application.name=APIGateway
server.port=8084

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Routes
#spring.cloud.gateway.server.webflux.routes=ORDER-SERVICE
#spring.cloud.gateway.server.webflux.routes=lb://ORDERSERVICE
#spring.cloud.gateway.server.webflux.routes=Path=/order/**
#
#spring.cloud.gateway.server.webflux.routes=PAYMENT-SERVICE
#spring.cloud.gateway.server.webflux.routes=lb://PAYMENTSERVICE
#spring.cloud.gateway.server.webflux.routes=Path=/payment/**
